# Generated by Django 5.2.6 on 2025-09-14 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=200)),
                ('billed_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(max_length=50)),
                ('insurer_name', models.CharField(max_length=100)),
                ('discharge_date', models.DateField()),
            ],
            options={
                'db_table': 'claims',
            },
        ),
        migrations.CreateModel(
            name='ClaimDetail',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('denial_reason', models.TextField(blank=True, null=True)),
                ('cpt_codes', models.CharField(blank=True, max_length=200, null=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='claims.claim')),
            ],
            options={
                'db_table': 'claim_details',
            },
        ),
        migrations.CreateModel(
            name='ClaimFlag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('flag_text', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='claims.claim')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'claim_flags',
            },
        ),
        migrations.CreateModel(
            name='ClaimNote',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('note_text', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='claims.claim')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'claim_notes',
            },
        ),
    ]
